### ISSUE TITLE
Onnx?

### ISSUE THREAD

**Issue by zelenooki87** [Yuehan717/RealViformer#1]
Thank you for a phenomenal project. I'm able to convert the model to onnx, but unfortunately I can't run inference with it. Can you help me with converting to onnx? or share the model's onnx file if you've converted it? It would mean a lot to me for easier use with a vapoursynth project. thank you so much in advance

**Comment by Yuehan717** [comment]
Thank you for your interest in our work. Unfortunately, we have not converted the model to onnx yet. I will look into this in the future, but I can't provide an estimated completion time at the moment. Thanks for your understanding.
